language: ruby
os: osx
env: OSX=10.11
osx_image: xcode7.3
rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - sudo chown -R "$USER" "$(brew --repo)"
  - git -C "$(brew --repo)" reset --hard origin/master
  - git -C "$(brew --repo)" clean -qxdff
  - brew update || brew update
  - mkdir -p "$(brew --repo)/Library/Taps/mcs07"
  - ln -s "$TRAVIS_BUILD_DIR" "$(brew --repo)/Library/Taps/mcs07/homebrew-cheminformatics"
  - cd "$(brew --repo)/Library/Taps/mcs07/homebrew-cheminformatics"
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/mcs07/homebrew-cheminformatics"
  - env | grep TRAVIS | tee /tmp/travis.env

install:
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

script:
  - brew test-bot
